### ISSUE TITLE
The bower can't fetch the dependent components of the polymer

### ISSUE THREAD

**Issue by yoichiro** [dart-lang/chromedeveditor#3851]
I'm using Chrome Dev Editor to develop my apps on Chromebook. From yesterday, my Chrome Dev Editor app can't complete to run the "bower". Especially, the bower can't fetch the dependent components. When checking the console in the DevTools, I found the following output.

(I filed the issue as this ticket by the advice I heard at Chrome Dev Editor community on G+: http://goo.gl/t6Ph9A)

```
[WARNING] spark.bower_fetcher: Some dependencies could not be resolved and have been skipped.
To fix, modify "dependencies" key in your bower.json as outlined below:

  "core-media-query": "Polymer/core-media-query#^0.5", <== unrecognized dependency specification; replace with a supported one
    "core-overlay": "Polymer/core-overlay#^0.5", <== unrecognized dependency specification; replace with a supported one
    "font-roboto": "Polymer/font-roboto#^0.5", <== unrecognized dependency specification; replace with a supported one
    "polymer": "Polymer/polymer#^0.5", <== unrecognized dependency specification; replace with a supported one
    "core-a11y-keys": "Polymer/core-a11y-keys#^0.5", <== unrecognized dependency specification; replace with a supported one
    "core-focusable": "Polymer/core-focusable#^0.5", <== unrecognized dependency specification; replace with a supported one
    "core-icon": "Polymer/core-icon#^0.5", <== unrecognized dependency specification; replace with a supported one
    "paper-ripple": "Polymer/paper-ripple#^0.5", <== unrecognized dependency specification; replace with a supported one
    "paper-shadow": "Polymer/paper-shadow#^0.5", <== unrecognized dependency specification; replace with a supported one﻿
```

**Comment by yoichiro** [comment]
This is a critical and fatal issue for developing Web application with Polymer as Chrome Dev Editor. I expect that this issue is caught by committers as quickly as possible.

**Comment by yoichiro** [comment]
I just investigated this issue. The Chrome Dev Editor is using the bower_semver library to check the version number of each dependent component written in bower.json.

https://github.com/dart-lang/chromedeveditor/blob/master/ide/web/lib/package_mgmt/bower_fetcher.dart#L571

The bower.json file of current Polymer components has like the following line:

```
"paper-ripple": "Polymer/paper-ripple#^0.5"
```

That is, the version number doesn't have the minor number. However, the bower_semver library expects the minor version number:

https://github.com/ussuri/bower_semver/blob/master/lib/src/patterns.dart#L11

Well, I think that we have two solutions:

(1) Committers of the Polymer add the minor version number against bower.json files of each Polymer copmonents.
(2) Committers of the bower_sember modify the pattern to check the version number without the minor number.

Can someone confirm my thinking above?

**Comment by srsaroop** [comment]
@yoichiro thanks for investigating this!
@gaurave Can you have look at this issue and confirm @yoichiro 's analysis?

**Comment by mmocny** [comment]
I just ran into this as well.  I haven't investigated if the analysis above is correct, but can confirm that it is quite surprising, since bower install step claims to complete successfully.

**Comment by yoichiro** [comment]
@mmocny Yes, I confirmed that the bower said that the installing was successfully when I tried to run 'bower install', however, actually all dependent components could not be installed, and the error messages 'unrecognized dependency specification; replace with a supported one' was displayed in the DevTools console panel.

**Comment by brycethorup** [comment]
Here is a temporary workaround, in your project's bower.json file change the line
`"paper-elements": "Polymer/paper-elements#latest"`
to
`"paper-elements": "Polymer/paper-elements#master"`

If I had to guess, there is probably something amiss with the implementation of the `#latest` dependency spec in the bower module.

**Comment by yoichiro** [comment]
@brycethorup Thank you for the sharing the workaround. Actually, when I tried to use the workaround like the following, I could do the "bower install" successfully.

```
{
  "name": "...",
  "version": "1.0.0",
  "dependencies": {
    "jquery": "~1.11.2",
    "paper-toast": "Polymer/paper-toast#master",
    "paper-button": "Polymer/paper-button#master"
  }
}
```

However, the following definition failed as my report first:

```
{
  "name": "...",
  "version": "1.0.0",
  "dependencies": {
    "jquery": "~1.11.2",
    "paper-toast": "Polymer/paper-toast#~0.5.3",
    "paper-button": "Polymer/paper-button#~0.5.3"
  }
}
```

It seems that there is the problem when we specify the concrete version number or "latest". And, I guess that this problem causes the strict regular expression I reported above...

**Comment by gaurave** [comment]
Looking into it, fix should be out soon

**Comment by gaurave** [comment]
The issue is fixed. It will be available in the next release.

**Comment by gaurave** [comment]
The issue is fixed and released. CDE will update itself. You can manually update it from 
chrome://extensions page.

**Comment by yoichiro** [comment]
@gaurave Thank you so much!
